# Generated by Django 4.2.1 on 2023-06-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customers_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
